### PR TITLE
Split main

### PR DESCRIPTION
**Pull request by behrica**
First try to solve #77 

This should be a refactoring without functional change, all tests still pass.

### CODE REVIEW

**Comment by borkdude** [comment]
@behrica Can you base your changes on the most recent master changes? 

Then if you run `bb gen-script` it will also take care of the other two files `(deps.bat, deps.clj)`.

**Comment by behrica** [comment]
I rebased it.

**Comment by borkdude** [comment]
@behrica This change looks good to me, conceptually. 

I think it would be good to add some tests so we can lock down a bit what you expect to be using, so we won't break that.

E.g. it isn't clear to me why we need the split between `deps/parsed-args->java-args` and `prepare-command`, the name of the latter could be `process-args` perhaps.

**Comment by behrica** [comment]
I think it would be good to do a bit more of work to make the function`parsed-args->java-args` more pure.
Specially because, it contains calls to `*exit-fn*`  which calls `System/exit` , we don't want this in an API...

This would require quite some work, to somehow externalize what several commands do, such as printing the tree (and exit)
Returning the main-args-as as map (what my change does), applies only to one command (start repl)
And this has a high chance of breaking something..

Not sure, how good the test suite is to cover this.

**Comment by borkdude** [comment]
Yes. This is why I think a test which tests the final API that you expect may a good starting point. Then we can work on the cases where deps.clj is not yet pure and address those cases. The name `parsed-args->java-args` probably also has to change, as the return value is map with several things, not only `java-args`?

**Comment by behrica** [comment]
I maen we shortcut this nice dataflow:

```(some-> command-line-args
          parse-args
          parsed-args->java-args
          prepare-process
          *process-fn*)
 ```
 
 by callsìing  `System/exit`, which is ugly and very "un-pure"

**Comment by behrica** [comment]
> Yes. This is why I think a test which tests the final API that you expect may a good starting point. Then we can work on the cases where deps.clj is not yet pure and address those cases. The name `parsed-args->java-args` probably also has to change, as the return value is map with several things, not only `java-args`?

Yes , name change is needed. I was not sure, what to call it.
We have "several intermediate representations" of the arguments to `clojure`.

1. "as typed by user"
2. ??
3. ??
4. as passed to `java` executable

Any idea wat 2, 3 could be called ?

**Comment by behrica** [comment]
and do we need indeed "2 intermediate" ? Or is one enough ?

**Comment by borkdude** [comment]
Do we need the split between 2,3,4? Why not just have 4 (in the exposed API, internally we could still split those, for whatever reason)?

**Comment by borkdude** [comment]
My experience is that when you can't come up with a good name, the problem definition / requirements just aren't clear.

**Comment by behrica** [comment]
II think we have only 3 and they make sense. look a this belo
It prints teh three steps.

0. user typed string as argument to `clojure CLI`    (seq of String)
1. same as 1), but as a structured map
2. we enrich the map with information from the `deps.edn`, resolving aliases and make classpath
3. we turn that into a seq of String to pass to java CLI
4. (call `java`)

(and in 2. we short-cut sometimes via System.exit)


```
(-> ["Stree"]
      (parse-args))
  ;; => {:mode :repl, :args ("Stree")}



  (-> ["Stree"]
      (parse-args)
      parsed-args->java-args)
  ;; => WARNING: Implicit use of clojure.main with options is deprecated, use -M
  ;;    {:args ("Stree"),
  ;;     :classpath
  ;;     "src:resources:/home/carsten/.m2/repository/org/clojure/clojure/1.10.3/clojure-1.10.3.jar:/home/carsten/.m2/repository/org/clojure/core.specs.alpha/0.2.56/core.specs.alpha-0.2.56.jar:/home/carsten/.m2/repository/org/clojure/spec.alpha/0.2.194/spec.alpha-0.2.194.jar",
  ;;     :java-cmd ["/usr/lib/jvm/java-17-openjdk/bin/java"],
  ;;     :java-opts nil,
  ;;     :main-opts nil,
  ;;     :jvm-cache-opts nil,
  ;;     :clojure-jvm-opts
  ;;     ["-Dclojure.basis=.cpcache/DF11EE9ECE61859619D37AF34FB981BE.basis"
  ;;      "-Dclojure.libfile=.cpcache/DF11EE9ECE61859619D37AF34FB981BE.libs"],
  ;;     :jvm-opts nil,
  ;;     :proxy-settings []}
      

  (-> ["Stree"]
      (parse-args)
      parsed-args->java-args
      prepare-process))
  ;; => WARNING: Implicit use of clojure.main with options is deprecated, use -M
  ;;    ["/usr/lib/jvm/java-17-openjdk/bin/java"
  ;;     "-Dclojure.basis=.cpcache/DF11EE9ECE61859619D37AF34FB981BE.basis"
  ;;     "-Dclojure.libfile=.cpcache/DF11EE9ECE61859619D37AF34FB981BE.libs"
  ;;     "-classpath"
  ;;     "src:resources:/home/carsten/.m2/repository/org/clojure/clojure/1.10.3/clojure-1.10.3.jar:/home/carsten/.m2/repository/org/clojure/core.specs.alpha/0.2.56/core.specs.alpha-0.2.56.jar:/home/carsten/.m2/repository/org/clojure/spec.alpha/0.2.194/spec.alpha-0.2.194.jar"
  ;;     "clojure.main"
  ;;     "Stree"]

````

**Comment by behrica** [comment]
Thats means we have naming like:

1. parse-clojure-args
2. resolve-args               (from deps.edn)
3. ->java-args

open for any better suggestion.

**Comment by behrica** [comment]
The naming looks good to me now:

```clojure
(some-> command-line-args
          parse-clojure-args
          resolve-args
          ->java-args
          *process-fn*)
```

**Comment by behrica** [comment]
Before going into a test suite for the "public funcion" I am interested (resolve-args), I would like now to solve the "short cutting issue". If we do not get that solved nicely, we don't have a pure function usable as API

All calls to *exit-fn* need to get out of `resolve-args`. Not sure how to tackle this.

**Comment by borkdude** [comment]
@behrica We can bind `*exit-fn*` to a non-exiting function in the publicly documented API function that should behave as a pure function.

**Comment by borkdude** [comment]
@behrica Or we can keep track of the exit code in a different way and only exit at the end of the main function with that exit code.

**Comment by borkdude** [comment]
I prefer to work from an existing test case and then change the code though. We can trigger the non-pure parts from that test and then solve it. We need to write these tests anyway. I'm pretty sure it's solvable. If you provide these tests, I'm willing to do the work. What I am most interested in is: what API do we expose. I don't want to leak too many internal details.

**Comment by behrica** [comment]
I am not able to develop in the test namespace.
The "test" alias (which has babashka.fs in classptha) runs the tests, so does not start a nrepl
And without the "test" alias, babashka.fs is missing.
How do you  work in ns borkdude.deps-test ?
Seem a stupid question, but maybe I miss some babashka magic ?

**Comment by borkdude** [comment]
@behrica Are you using emacs?

**Comment by borkdude** [comment]
OK, if you now merge with master, I've added a `.dir-locals` which should help with `cider-jack-in` to add test dependencies. Babashka.fs is just a normal JVM library, but is also included with babashka, hence the name.

**Comment by behrica** [comment]
In any case, it is kind of impossible to write the tests know, given the "impure" situation of the ` resolve-args` functions. (see above)

I would like to write tests which :
---
given a CLI input and given a certain deps.dn file
I expect that the java args generated would be xxxx
--

This would know require a lot of magic to "mock" the deps.edn file as input, not sure if possible at all.

**Comment by borkdude** [comment]
> This would know require a lot of magic to "mock" the deps.edn file as input

You can use the `-Sdeps-file ...` argument that allows setting a different deps.edn file.

**Comment by borkdude** [comment]
> This will "execute the tests" at jack-in time....

Have you tried it? It works for me.

**Comment by behrica** [comment]
Solving this requires 2 aliases, one set the test class path only, the other  one set classpath and runs tests.

**Comment by behrica** [comment]
I have done "C-u cider-jack-in" and added "-A:test"  by hand   which I suppose is the same.

But try it know.....

**Comment by behrica** [comment]
Sorry, you are right, It is not the same.
Working now. Thanks.

**Comment by behrica** [comment]
The tests  can be written by specifying -Sdeps directly, this avoids reliance on a deps.edn file:

so like this
```
(is (= "-Dfoo=foo bar"
       (second
        (->
         ["-Sdeps" "{:aliases {:my-alias {:jvm-opts [\"-Dfoo=foo bar\"]}}}" "-A:my-alias"]
         (deps/parse-clojure-args)
         (deps/resolve-args)
         (deps/->java-args)))))
```

It tests teh tree functions together, not ideal.

**Comment by borkdude** [comment]
@behrica What I would like you to write is a test as a specification of what you want from deps.clj, nothing more than that actually. The test then forms a contract so we won't break it in the future.

**Comment by behrica** [comment]
But this is teh functionality I would need. To test the API function alone could look like this:

```
(is (= ["-Dfoo=foo bar"])
    (->
     {:mode :repl,
      :deps-data "{:aliases {:my-alias {:jvm-opts [\"-Dfoo=foo bar\"]}}}",
      :repl-aliases [":my-alias"]}

     deps/resolve-args

     :jvm-cache-opts))
```
But this would require that we consider the intermediate maps as "stable", which requires some thinking.
I did them at least very ad-hoc, looking at existing code, and not thinking about the correct abstraction

**Comment by behrica** [comment]
> @behrica What I would like you to write is a test as a specification of what you want from deps.clj, nothing more than that actually. The test then forms a contract so we won't break it in the future.

Yes, I understand this.
But the expected result of the test depends on the existence of a local `deps.edn` file and its content.
So I need to know a way how to "mock this" , unless we make the supposed API function fully "pure" first
(= not relying on local files)

**Comment by behrica** [comment]
It should be possible to pass the deps.edn data as you said (oer point to file).
Should I assume that the refactoring above will be merged ?
I need a function to write the tests against.

So I would add a few tests to this PR, and then you decide how to go ahead ?

**Comment by borkdude** [comment]
Question: I feel that I don't see the complete picture. When reading #77 it seems to me that you only need a transformation of CLI arguments to arguments to start a Java process (without starting that process, since that's what you want to do yourself). Isn't that sufficient? Why do you need the intermediate representation?

About mocking:

You can "mock" with a deps.edn map like this:

Either:

- write the deps.edn map to a temporary file and set `-Sdeps-file temp-file` 
- or set `-Sdeps-file nil` and provide `-Sdeps` with the deps-map

I've already mentioned `-Sdeps-file` before in this thread [here](https://github.com/borkdude/deps.clj/pull/78#issuecomment-1298725088).

**Comment by behrica** [comment]
I added 3 tests, which cover the main use case from my point of view.
Given some deps.edn data and a list of aliases, we need to know the full classpath and the full list of java JVM args

Any more tests would be variants of this.

**Comment by behrica** [comment]
> Question: I feel that I don't see the complete picture. When reading #77 it seems to me that you only need a transformation of CLI arguments to arguments to start a Java process (without starting that process, since that's what you want to do yourself). Isn't that sufficient? Why do you need the intermediate representation?
> 
> About mocking:
> 
> You can "mock" with a deps.edn map like this:
> 
> Either:
> 
> * write the deps.edn map to a temporary file and set `-Sdeps-file temp-file`
> * or set `-Sdeps-file nil` and provide `-Sdeps` with the deps-map
> 
> I've already mentioned `-Sdeps-file` before in this thread [here](https://github.com/borkdude/deps.clj/pull/78#issuecomment-1298725088).

Mocking is solved.

I don't need the intermediate representation.
But to have  it, was the simplest thing to do to "split" the `-main` function.

**Comment by borkdude** [comment]
> Given some deps.edn data and a list of aliases, we need to know the full classpath and the full list of java JVM args

Ah, so you don't even need to parse the command line arguments as we do normally then? This clarifies a lot.

So the API function we could need would look like:

```
(defn foo [{:keys [deps-map aliases]}]) 
```

and returns `{:java-args [...] :classpath ....}`

That's all right?

A cleaner way to achieve that would be to write this function, and use the extracted intermediate functions (but make those private to not leak any details) in the implementation of that function).
Then we can use this function in the tests as well.

**Comment by behrica** [comment]
And I think the API should not operate on "list of strings" but on clojure maps.
The raw input is "list of strings" and the "end" as well.
but I believe the API should not work on those directly, but on some map representation of it.
You have done it already for converting "input" to maps.
But the the raw input is "enriched"  (resolved from deps.edn) , and we should in my view have a map representation of those, first. You cod had that in form of local vars in a "let". I justed added them into a map.

But maybe it is not needed-

**Comment by behrica** [comment]
> > Given some deps.edn data and a list of aliases, we need to know the full classpath and the full list of java JVM args
> 
> Ah, so you don't even need to parse the command line arguments as we do normally then? This clarifies a lot.
> 
Indeed. We start a python process first, which starts the JVM. So there is no standard Clojure command line parsing.
We will find a way to "pass" the aliases to python, which passes them to java.

image

I want at the end that the python function, which starts the JVM accepts a list of aliases (strings), and then the right thing happens (using the local deps.edn file)

**Comment by behrica** [comment]
The python code does this already now for the classpath.
It shells out and calls `clj -Spath`  to construct the classpath.

We have nothing like this for the JVM args, and so aliases are teh correct way to do this, I think.

If deps.clj would have an API to get the classpath, we would then use this.
(after figuring out how to call this from Java without having clojure....)
Probably downloading an uberjar and calling clojure from java.... But this should work at the end.

**Comment by behrica** [comment]
The goal is to solve this issue:

https://github.com/behrica/clojurebridge/issues/4

**Comment by behrica** [comment]
The goal is to solve this issue:

https://github.com/behrica/clojurebridge/issues/4

**Comment by behrica** [comment]
I am just wondering if this is teh correct intermidiate format to base the API on:

```
{:version "1.11.1.1165"
 :config-files ["/usr/share/clojure/deps.edn" "/home/carsten/.clojure/deps.edn" "deps.edn" ]
 :config-user "/home/carsten/.clojure/deps.edn"
 :config-project "deps.edn"
 :install-dir "/usr/share/clojure"
 :config-dir "/home/carsten/.clojure"
 :cache-dir ".cpcache"
 :force false
 :repro false
 :main-aliases ""
 :repl-aliases ":jdk"}
```

Maybe an API function should take this as input and produce all needed to call java in a certain format. (ideally a map and not a "flat list of strings")

**Comment by behrica** [comment]
> I am just wondering if this is teh correct intermidiate format to base the API on:
> 
> ```
> {:version "1.11.1.1165"
>  :config-files ["/usr/share/clojure/deps.edn" "/home/carsten/.clojure/deps.edn" "deps.edn" ]
>  :config-user "/home/carsten/.clojure/deps.edn"
>  :config-project "deps.edn"
>  :install-dir "/usr/share/clojure"
>  :config-dir "/home/carsten/.clojure"
>  :cache-dir ".cpcache"
>  :force false
>  :repro false
>  :main-aliases ""
>  :repl-aliases ":jdk"}
> ```
> 
> Maybe an API function should take this as input and produce all needed to call java in a certain format. (ideally a map and not a "flat list of strings")

But this would put more work on the "caller". For example, the first list of :config-files locations can be "calculated" as well.

**Pull request closed without merging**
